//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPackageBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPackageBuilder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Product]
        ///number=###SHORTNAME###
        ///revision=###REVISION###
        ///family=###FAMILY###
        ///description=###DESCRIPTION###
        ///
        ///release_key=AVP_NON_WAP_02_01.key
        ///platform = avp
        ///category = game
        ///version = 1.0
        ///push=0
        ///copyright_year = 2015
        ///
        ///
        ///[Build]
        ///build_module   = buildAscent
        ///.
        /// </summary>
        internal static string build {
            get {
                return ResourceManager.GetString("build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context files (*.epbcontext)|*.epbcontext|All files (*.*)|*.*.
        /// </summary>
        internal static string ContextFilesFilter {
            get {
                return ResourceManager.GetString("ContextFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssemblyProjects
        ///Assets
        ///EGMResources
        ///Paytables
        ///ProjectSettings
        ///Registries
        ///SIF
        ///AssemblyProjects.config
        ///GameVersion.txt
        ///SystemConfig.xml.
        /// </summary>
        internal static string copylist {
            get {
                return ResourceManager.GetString("copylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set PYTHON_CMD=c:\python32\python.exe
        ///if not exist %PYTHON_CMD% set PYTHON_CMD=%PYTHON32%\python.exe
        ///if not exist %PYTHON_CMD% set PYTHON_CMD=python.exe
        ///
        ///%PYTHON_CMD% -B bin\buildWrapper.py %1 %2.
        /// </summary>
        internal static string GameFULL {
            get {
                return ResourceManager.GetString("GameFULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setlocal
        ///set CURRENT_DIR=%~dp0
        ///set CURRENT_DIR=%CURRENT_DIR:~0,-1%
        ///set GAME_NAME=Game###FULLNAME###
        ///set GAME_NAME_SHORT=Game-###SHORTNAME###
        ///
        ///REM Sets Game Output dir relative to game&apos;s dir.
        ///set DEVELOPMENT_DIR=%CURRENT_DIR%\..\..
        ///for /f &quot;delims=&quot; %%a in (&quot;%DEVELOPMENT_DIR%&quot;) do set DEVELOPMENT_DIR=%%~fa
        ///set GAME_OUTPUT_DIR=%DEVELOPMENT_DIR%\Games\%GAME_NAME_SHORT%
        ///
        ///REM To override output dir, define it here.
        ///REM To prevent extra copy, undefine it here.
        ///REM set GAME_OUTPUT_DIR=
        ///
        ///set BIN_DIR=% [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GameSHORT {
            get {
                return ResourceManager.GetString("GameSHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build:###BUILD###
        ///Date:###DATE###
        ///SDK:###SDK###
        ///IGTUnity:###IGTUNITY###.
        /// </summary>
        internal static string GameVersion {
            get {
                return ResourceManager.GetString("GameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon1 {
            get {
                object obj = ResourceManager.GetObject("Icon1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
